#!/bin/bash
# Ralph AFK Loop Script with Full Feedback Loops for Go Projects
# Runs Claude in Docker sandbox with comprehensive quality checks
# Optimized for high-quality Golang development

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <iterations>"
  echo "Example: $0 20"
  exit 1
fi

# Ensure review.txt exists
if [ ! -f "review.txt" ]; then
  echo "# Code Review Log" > review.txt
  echo "# Generated by Ralph Loop with Feedback (Go)" >> review.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> review.txt
  echo "" >> review.txt
fi

# Ensure progress.txt exists
if [ ! -f "progress.txt" ]; then
  echo "# Progress Log" > progress.txt
  echo "# Generated by Ralph Loop (Go)" >> progress.txt
  echo "# Date: $(date '+%Y-%m-%d')" >> progress.txt
  echo "" >> progress.txt
fi

echo "=========================================="
echo "Ralph Loop with Full Feedback Loops (Go)"
echo "=========================================="
echo "Iterations: $1"
echo "Model: Claude Opus (latest)"
echo ""
echo "Feedback Loops Enabled:"
echo "  - Compilation (go build)"
echo "  - Static analysis (go vet)"
echo "  - Linting (golangci-lint)"
echo "  - Unit tests (go test)"
echo "  - Race detection (go test -race)"
echo "  - Code coverage"
echo "  - Formatting (gofmt/goimports)"
echo "=========================================="
echo ""

for ((i=1; i<=$1; i++)); do
  echo "=== Iteration $i of $1 ==="
  echo "Starting fresh Claude context..."
  echo ""

  result=$(docker sandbox run claude --model opus --permission-mode acceptEdits -p "@prd.json @progress.txt @review.txt

========================================
GO CODE QUALITY EXPECTATIONS
========================================
Go emphasizes simplicity, readability, and correctness.
Rob Pike said: 'Clear is better than clever.'

This codebase will outlive you. Every shortcut you take becomes
someone else's burden. Every hack compounds into technical debt
that slows the whole team down.

Go proverbs to live by:
- Don't communicate by sharing memory; share memory by communicating.
- Channels orchestrate; mutexes serialize.
- The bigger the interface, the weaker the abstraction.
- Make the zero value useful.
- A little copying is better than a little dependency.
- Errors are values.
- Don't just check errors, handle them gracefully.
- Don't panic.

========================================
ENVIRONMENT SETUP (REQUIRED FIRST)
========================================

1. VERIFY GO INSTALLATION:
   - Check Go version: go version
   - Ensure Go 1.21+ for latest features
   - Verify GOPATH and GOMODULE settings

2. INITIALIZE/VERIFY MODULE:
   - Check if go.mod exists
   - If not: go mod init <module-name>
   - Download dependencies: go mod download
   - Tidy dependencies: go mod tidy

3. INSTALL DEV TOOLS (if not available):
   - golangci-lint: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
   - goimports: go install golang.org/x/tools/cmd/goimports@latest
   - mockgen (if using mocks): go install go.uber.org/mock/mockgen@latest
   - staticcheck: go install honnef.co/go/tools/cmd/staticcheck@latest

4. VERIFY WORKSPACE:
   - Run: go mod verify
   - Ensure all dependencies are clean

========================================
TASK WORKFLOW
========================================

1. READ CONTEXT:
   - Read prd.json to understand all tasks and their 'passes' status
   - Read progress.txt to see what was done in previous iterations
   - Read review.txt to see any review feedback

2. CHOOSE NEXT TASK (prioritize in this order):
   - Architectural decisions and core abstractions
   - Interface definitions (keep them small!)
   - Integration points between packages
   - Unknown unknowns and spike work
   - Standard features and implementation
   - Polish, cleanup, and quick wins
   - Choose a task where 'passes' is false

3. WRITE TESTS FIRST (TDD approach):
   - Create *_test.go files alongside implementation
   - Use table-driven tests for comprehensive coverage
   - Include: happy path, edge cases, error handling
   - Use subtests with t.Run() for organization
   - Run tests to confirm they fail (red phase):
     go test -v ./...

4. IMPLEMENT THE FEATURE:
   - Follow Go conventions and idioms
   - Keep functions small and focused
   - Return errors, don't panic
   - Use meaningful variable names
   - Comment exported functions/types (godoc style)
   - Prefer composition over inheritance
   - Use interfaces at consumption site, not definition

5. RUN ALL FEEDBACK LOOPS (REQUIRED before commit):

   a) FORMAT CODE:
      gofmt -w .
      goimports -w .
      
   b) BUILD (type checking):
      go build ./...
      
   c) VET (static analysis):
      go vet ./...
      
   d) LINT (comprehensive checks):
      golangci-lint run ./...
      
      If golangci-lint is not available, use:
      staticcheck ./...
      
   e) UNIT TESTS:
      go test -v ./...
      
   f) RACE DETECTION:
      go test -race ./...
      
   g) COVERAGE:
      go test -coverprofile=coverage.out ./...
      go tool cover -func=coverage.out
      
      Aim for >80% coverage on business logic.
      
   h) SECURITY (optional but recommended):
      go install golang.org/x/vuln/cmd/govulncheck@latest
      govulncheck ./...

   DO NOT COMMIT IF ANY FEEDBACK LOOP FAILS.
   Fix issues first, then re-run all checks.

6. UPDATE PRD:
   - Set 'passes' to true for the completed task
   - Add any new subtasks discovered during implementation

7. UPDATE PROGRESS FILE:
   Append to progress.txt:
   - Task completed and PRD item reference
   - Key decisions made and reasoning
   - Files changed
   - Test results summary
   - Any blockers or notes for next iteration
   Keep entries concise.

8. COMMIT YOUR CHANGES:
   - Use descriptive commit message
   - Reference the PRD item ID
   - Only commit if ALL feedback loops pass

9. APPEND REVIEW TO review.txt:
   ## [TASK-ID]: Task Description
   **Status:** PASSED/NEEDS_ATTENTION
   **Tests Written:** (list new test functions)
   **Test Results:** go test output summary
   **Race Detection:** PASSED/FAILED
   **Coverage:** X% (target areas)
   **Vet/Lint:** PASSED/FAILED (note any suppressions)
   **Build:** PASSED/FAILED
   **Findings:** Your detailed notes
   **Recommendations:** Any suggestions for future iterations

========================================
GO-SPECIFIC BEST PRACTICES
========================================

ERROR HANDLING:
- Always check errors
- Wrap errors with context: fmt.Errorf(\"doing X: %w\", err)
- Use errors.Is() and errors.As() for error inspection
- Define sentinel errors for expected conditions
- Never ignore errors silently (use _ = explicitly if intentional)

CONCURRENCY:
- Use channels for communication
- Use sync.Mutex only when necessary
- Always use -race flag in tests
- Context should be first parameter
- Cancel contexts when done
- Use sync.WaitGroup for goroutine coordination
- Prefer sync.Once for one-time initialization

INTERFACES:
- Keep interfaces small (1-3 methods ideal)
- Define interfaces where they're used, not where implemented
- Accept interfaces, return structs
- Use io.Reader, io.Writer when possible

PACKAGES:
- Avoid package-level state
- Use internal/ for private packages
- Keep cmd/ for entry points
- Avoid circular dependencies
- One package = one purpose

TESTING:
- Use table-driven tests
- Use testify/assert or testify/require for assertions
- Mock external dependencies
- Test exported API, not internals
- Use t.Parallel() for independent tests
- Benchmark critical paths

DOCUMENTATION:
- Every exported symbol needs a doc comment
- Start with the name: \"Handler processes HTTP requests...\"
- Include examples in *_test.go with Example prefix
- Use godoc conventions

========================================
RULES
========================================

- ONLY WORK ON A SINGLE TASK PER ITERATION
- Small steps compound into big progress
- Quality over speed - especially when AFK
- Never commit with failing tests or vet errors
- Each iteration is a fresh context - progress.txt is your memory
- Git history shows what previous iterations did
- go fmt is not negotiable - always format before commit
- Race conditions are bugs - always test with -race

If ALL tasks in prd.json have 'passes': true, output <promise>COMPLETE</promise>.")

  echo "$result"
  echo ""

  if [[ "$result" == *"<promise>COMPLETE</promise>"* ]]; then
    echo "=========================================="
    echo "All PRD tasks completed after $i iterations!"
    echo "Review results in review.txt"
    echo "Progress history in progress.txt"
    echo "=========================================="
    exit 0
  fi

  echo "--- Iteration $i complete, starting next fresh context ---"
  echo ""
done

echo "=========================================="
echo "Reached maximum iterations ($1)."
echo "Some tasks may still have 'passes': false."
echo "Check prd.json, progress.txt, and review.txt"
echo "=========================================="
